// <auto-generated />
using System;
using DUNES.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DUNES.API.Migrations
{
    [DbContext(typeof(appWmsDbContext))]
    [Migration("20260129171222_mig202601291211")]
    partial class mig202601291211
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DUNES.API.ModelsWMS.Admin.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AppName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BusinessKey")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ChangedColumns")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventDateUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("char(6)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JsonNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonOld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Module")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("dbo");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_AuditLog_TraceId");

                    b.HasIndex("BusinessKey", "EventDateUtc")
                        .HasDatabaseName("IX_AuditLog_BusinessKey_Date");

                    b.HasIndex("Module", "EventDateUtc")
                        .HasDatabaseName("IX_AuditLog_Module_Date");

                    b.HasIndex("UserName", "EventDateUtc")
                        .HasDatabaseName("IX_AuditLog_User_Date");

                    b.HasIndex("SchemaName", "TableName", "EventType", "EventDateUtc")
                        .HasDatabaseName("IX_AuditLog_Table_Type_Date");

                    b.HasIndex("SchemaName", "TableName", "PrimaryKey", "EventDateUtc")
                        .HasDatabaseName("IX_AuditLog_Table_PK_Date");

                    b.ToTable("AuditLog", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_EventType", "EventType IN ('INSERT','UPDATE','DELETE')");
                        });
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Bines", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<int>("LocationsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacksId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationsId");

                    b.HasIndex("RacksId");

                    b.HasIndex(new[] { "Idcompany" }, "IX_bines_Idcompany");

                    b.ToTable("bines", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Cities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcountry")
                        .HasColumnType("int");

                    b.Property<int>("Idstate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcountry" }, "IX_cities_Idcountry");

                    b.HasIndex(new[] { "Idstate" }, "IX_cities_Idstate");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompaniesContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContractCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCatalogMode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompaniesContract");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("companyId");

                    b.Property<int>("Idcity")
                        .HasColumnType("int");

                    b.Property<int>("Idcountry")
                        .HasColumnType("int");

                    b.Property<int>("Idstate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phone");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("website");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcity" }, "IX_company_Idcity");

                    b.HasIndex(new[] { "Idcountry" }, "IX_company_Idcountry");

                    b.HasIndex(new[] { "Idstate" }, "IX_company_Idstate");

                    b.ToTable("company", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompanyClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("companyId");

                    b.Property<int>("Idcity")
                        .HasColumnType("int");

                    b.Property<int>("Idcountry")
                        .HasColumnType("int");

                    b.Property<int>("Idstate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phone");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("website");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcity" }, "IX_companyClient_Idcity");

                    b.HasIndex(new[] { "Idcountry" }, "IX_companyClient_Idcountry");

                    b.HasIndex(new[] { "Idstate" }, "IX_companyClient_Idstate");

                    b.ToTable("companyClient", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompanyClientDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DivisionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idcompanyclient")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcompanyclient" }, "IX_companyClientDivision_Idcompanyclient");

                    b.ToTable("companyClientDivision", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Generalparameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("parameterId");

                    b.Property<string>("Parametername")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("parametername");

                    b.Property<string>("Parametervalue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("parametervalue");

                    b.HasKey("Id");

                    b.ToTable("generalparameters", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventoryTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnHand")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Zebrainvassociated")
                        .HasColumnType("int")
                        .HasColumnName("zebrainvassociated");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcompany" }, "IX_inventoryTypes_Idcompany");

                    b.ToTable("inventoryTypes", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorycategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "companyId" }, "IX_inventorycategories_Idcompany");

                    b.ToTable("inventorycategories", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorydetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idbin")
                        .HasColumnType("int");

                    b.Property<int?>("IdbinNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iddivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iditem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idlocation")
                        .HasColumnType("int");

                    b.Property<int>("Idrack")
                        .HasColumnType("int");

                    b.Property<int?>("IdrackNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idstatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdstatusNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idtype")
                        .HasColumnType("int");

                    b.Property<int?>("IdtypeNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("Serialid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("serialid");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int")
                        .HasColumnName("totalQty");

                    b.HasKey("Id");

                    b.HasIndex("IdbinNavigationId");

                    b.HasIndex("IdrackNavigationId");

                    b.HasIndex("IdstatusNavigationId");

                    b.HasIndex("IdtypeNavigationId");

                    b.HasIndex(new[] { "Idbin" }, "IX_inventorydetail_Idbin");

                    b.HasIndex(new[] { "Idcompany" }, "IX_inventorydetail_Idcompany");

                    b.HasIndex(new[] { "Idlocation" }, "IX_inventorydetail_Idlocation");

                    b.HasIndex(new[] { "Idrack" }, "IX_inventorydetail_Idrack");

                    b.HasIndex(new[] { "Idstatus" }, "IX_inventorydetail_Idstatus");

                    b.HasIndex(new[] { "Idtype" }, "IX_inventorydetail_Idtype");

                    b.ToTable("inventorydetail", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorymovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Createdby")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("createdby");

                    b.Property<DateTime>("Datecreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("datecreated");

                    b.Property<int>("Idbin")
                        .HasColumnType("int");

                    b.Property<int?>("IdbinNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iddivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iditem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idlocation")
                        .HasColumnType("int");

                    b.Property<int>("Idrack")
                        .HasColumnType("int");

                    b.Property<int?>("IdrackNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idstatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdstatusNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("IdtransactionDetail")
                        .HasColumnType("int")
                        .HasColumnName("idtransactionDetail");

                    b.Property<int>("IdtransactionHead")
                        .HasColumnType("int");

                    b.Property<int>("Idtransactionconcept")
                        .HasColumnType("int");

                    b.Property<int?>("IdtransactionconceptNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idtransactiontype")
                        .HasColumnType("int");

                    b.Property<int>("Idtype")
                        .HasColumnType("int");

                    b.Property<int?>("IdtypeNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("Qtybalance")
                        .HasColumnType("int")
                        .HasColumnName("qtybalance");

                    b.Property<int>("Qtyinput")
                        .HasColumnType("int")
                        .HasColumnName("qtyinput");

                    b.Property<int>("Qtyoutput")
                        .HasColumnType("int")
                        .HasColumnName("qtyoutput");

                    b.Property<string>("Serialid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("serialid");

                    b.HasKey("Id");

                    b.HasIndex("IdbinNavigationId");

                    b.HasIndex("IdrackNavigationId");

                    b.HasIndex("IdstatusNavigationId");

                    b.HasIndex("IdtransactionconceptNavigationId");

                    b.HasIndex("IdtypeNavigationId");

                    b.HasIndex(new[] { "Idbin" }, "IX_inventorymovement_Idbin");

                    b.HasIndex(new[] { "Idcompany" }, "IX_inventorymovement_Idcompany");

                    b.HasIndex(new[] { "Idlocation" }, "IX_inventorymovement_Idlocation");

                    b.HasIndex(new[] { "Idrack" }, "IX_inventorymovement_Idrack");

                    b.HasIndex(new[] { "Idstatus" }, "IX_inventorymovement_Idstatus");

                    b.HasIndex(new[] { "IdtransactionHead" }, "IX_inventorymovement_IdtransactionHead");

                    b.HasIndex(new[] { "Idtransactionconcept" }, "IX_inventorymovement_Idtransactionconcept");

                    b.HasIndex(new[] { "Idtransactiontype" }, "IX_inventorymovement_Idtransactiontype");

                    b.HasIndex(new[] { "Idtype" }, "IX_inventorymovement_Idtype");

                    b.HasIndex(new[] { "IdtransactionDetail" }, "IX_inventorymovement_idtransactionDetail");

                    b.ToTable("inventorymovement", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idbin")
                        .HasColumnType("int");

                    b.Property<int?>("IdbinNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iddivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idenctransaction")
                        .HasColumnType("int");

                    b.Property<string>("Iditem")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idlocation")
                        .HasColumnType("int");

                    b.Property<int>("Idrack")
                        .HasColumnType("int");

                    b.Property<int?>("IdrackNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idstatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdstatusNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idtype")
                        .HasColumnType("int");

                    b.Property<int?>("IdtypeNavigationId")
                        .HasColumnType("int");

                    b.Property<int>("Idtypetransaction")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("Serialid")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("serialid");

                    b.Property<int>("TotalQty")
                        .HasColumnType("int")
                        .HasColumnName("totalQty");

                    b.HasKey("Id");

                    b.HasIndex("IdbinNavigationId");

                    b.HasIndex("IdrackNavigationId");

                    b.HasIndex("IdstatusNavigationId");

                    b.HasIndex("IdtypeNavigationId");

                    b.HasIndex(new[] { "Idbin" }, "IX_inventorytransactionDetail_Idbin");

                    b.HasIndex(new[] { "Idcompany" }, "IX_inventorytransactionDetail_Idcompany");

                    b.HasIndex(new[] { "Idenctransaction" }, "IX_inventorytransactionDetail_Idenctransaction");

                    b.HasIndex(new[] { "Idlocation" }, "IX_inventorytransactionDetail_Idlocation");

                    b.HasIndex(new[] { "Idrack" }, "IX_inventorytransactionDetail_Idrack");

                    b.HasIndex(new[] { "Idstatus" }, "IX_inventorytransactionDetail_Idstatus");

                    b.HasIndex(new[] { "Idtype" }, "IX_inventorytransactionDetail_Idtype");

                    b.HasIndex(new[] { "Idtypetransaction" }, "IX_inventorytransactionDetail_Idtypetransaction");

                    b.ToTable("inventorytransactionDetail", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionHdr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datecreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("datecreated");

                    b.Property<DateTime>("Dateprocessed")
                        .HasColumnType("datetime2")
                        .HasColumnName("dateprocessed");

                    b.Property<string>("Documentreference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("documentreference");

                    b.Property<string>("IdUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUserprocess")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iddivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idtransactionconcept")
                        .HasColumnType("int");

                    b.Property<int?>("IdtransactionconceptNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("observations");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit")
                        .HasColumnName("processed");

                    b.HasKey("Id");

                    b.HasIndex("IdtransactionconceptNavigationId");

                    b.HasIndex(new[] { "Idcompany" }, "IX_inventorytransactionHdr_Idcompany");

                    b.HasIndex(new[] { "Idtransactionconcept" }, "IX_inventorytransactionHdr_Idtransactionconcept");

                    b.ToTable("inventorytransactionHdr", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CompanyClientId")
                        .HasColumnType("int");

                    b.Property<int>("InventorycategoriesId")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.Property<bool>("isRepairable")
                        .HasColumnType("bit");

                    b.Property<bool>("isSerialized")
                        .HasColumnType("bit");

                    b.Property<string>("itemDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("serialnumber")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyClientId");

                    b.HasIndex("InventorycategoriesId");

                    b.HasIndex("companyId", "sku")
                        .IsUnique()
                        .HasFilter("[sku] IS NOT NULL");

                    b.ToTable("items");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Itemstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcompany" }, "IX_itemstatus_Idcompany");

                    b.ToTable("itemstatus", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Locationclients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idlocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcompany" }, "IX_locationclients_Idcompany");

                    b.HasIndex(new[] { "Idlocation" }, "IX_locationclients_Idlocation");

                    b.ToTable("locationclients", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Locations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("address");

                    b.Property<int>("Idcity")
                        .HasColumnType("int");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<int>("Idcountry")
                        .HasColumnType("int");

                    b.Property<int>("Idstate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phone");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcity" }, "IX_locations_Idcity");

                    b.HasIndex(new[] { "Idcompany" }, "IX_locations_Idcompany");

                    b.HasIndex(new[] { "Idcountry" }, "IX_locations_Idcountry");

                    b.HasIndex(new[] { "Idstate" }, "IX_locations_Idstate");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Racks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<int>("LocationsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LocationsId");

                    b.HasIndex(new[] { "Idcompany" }, "IX_racks_Idcompany");

                    b.ToTable("racks", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.StatesCountries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcountry")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcountry" }, "IX_statesCountries_Idcountry");

                    b.ToTable("statesCountries", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Transactionconcepts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("companyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("companyId");

                    b.ToTable("Transactionconcepts");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Transactiontypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Isinput")
                        .HasColumnType("bit")
                        .HasColumnName("isinput");

                    b.Property<bool>("Isoutput")
                        .HasColumnType("bit")
                        .HasColumnName("isoutput");

                    b.Property<bool>("Ispreconsumption")
                        .HasColumnType("bit")
                        .HasColumnName("ispreconsumption");

                    b.Property<string>("Match")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("match");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idcompany" }, "IX_transactiontypes_Idcompany");

                    b.ToTable("transactiontypes", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Warehouseorganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Idbin")
                        .HasColumnType("int");

                    b.Property<int>("Idcompany")
                        .HasColumnType("int");

                    b.Property<string>("Idcompanyclient")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Iddivision")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Idlocation")
                        .HasColumnType("int");

                    b.Property<int>("Idrack")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Idbin" }, "IX_warehouseorganization_Idbin");

                    b.HasIndex(new[] { "Idcompany" }, "IX_warehouseorganization_Idcompany");

                    b.HasIndex(new[] { "Idlocation" }, "IX_warehouseorganization_Idlocation");

                    b.HasIndex(new[] { "Idrack" }, "IX_warehouseorganization_Idrack");

                    b.ToTable("warehouseorganization", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.ui_translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lang")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TValue")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Ui_translation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Transactions.Itemsbybin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinesId")
                        .HasColumnType("int")
                        .HasColumnName("binesId");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("Idcompanyclient")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Itemid")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("itemid");

                    b.Property<string>("tagName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BinesId" }, "IX_itemsbybin_binesId");

                    b.HasIndex(new[] { "CompanyId" }, "IX_itemsbybin_companyId");

                    b.ToTable("itemsbybin", (string)null);
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Bines", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Bines")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Locations", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Racks", "Racks")
                        .WithMany()
                        .HasForeignKey("RacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("Locations");

                    b.Navigation("Racks");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Cities", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Countries", "IdcountryNavigation")
                        .WithMany("Cities")
                        .HasForeignKey("Idcountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.StatesCountries", "IdstateNavigation")
                        .WithMany("Cities")
                        .HasForeignKey("Idstate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcountryNavigation");

                    b.Navigation("IdstateNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompaniesContract", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.CompanyClient", "CompanyClientNavegation")
                        .WithMany()
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "CompanyNavegation")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyClientNavegation");

                    b.Navigation("CompanyNavegation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Company", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Cities", "IdcityNavigation")
                        .WithMany("Company")
                        .HasForeignKey("Idcity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Countries", "IdcountryNavigation")
                        .WithMany("Company")
                        .HasForeignKey("Idcountry")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.StatesCountries", "IdstateNavigation")
                        .WithMany("Company")
                        .HasForeignKey("Idstate")
                        .IsRequired();

                    b.Navigation("IdcityNavigation");

                    b.Navigation("IdcountryNavigation");

                    b.Navigation("IdstateNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompanyClient", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Cities", "CityNavegation")
                        .WithMany()
                        .HasForeignKey("Idcity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Countries", "CountryNavegation")
                        .WithMany()
                        .HasForeignKey("Idcountry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.StatesCountries", "StateNavegation")
                        .WithMany()
                        .HasForeignKey("Idstate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CityNavegation");

                    b.Navigation("CountryNavegation");

                    b.Navigation("StateNavegation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventoryTypes", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("InventoryTypes")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorycategories", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Inventorycategories")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorydetail", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Bines", "IdbinNavigation")
                        .WithMany()
                        .HasForeignKey("IdbinNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Inventorydetail")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Locations", "IdlocationNavigation")
                        .WithMany("Inventorydetail")
                        .HasForeignKey("Idlocation")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Racks", "IdrackNavigation")
                        .WithMany()
                        .HasForeignKey("IdrackNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Itemstatus", "IdstatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdstatusNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventoryTypes", "IdtypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdtypeNavigationId");

                    b.Navigation("IdbinNavigation");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("IdlocationNavigation");

                    b.Navigation("IdrackNavigation");

                    b.Navigation("IdstatusNavigation");

                    b.Navigation("IdtypeNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Inventorymovement", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Bines", "IdbinNavigation")
                        .WithMany()
                        .HasForeignKey("IdbinNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Inventorymovement")
                        .HasForeignKey("Idcompany")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Locations", "IdlocationNavigation")
                        .WithMany("Inventorymovement")
                        .HasForeignKey("Idlocation")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Racks", "IdrackNavigation")
                        .WithMany()
                        .HasForeignKey("IdrackNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Itemstatus", "IdstatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdstatusNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventorytransactionDetail", "IdtransactionDetailNavigation")
                        .WithMany("Inventorymovement")
                        .HasForeignKey("IdtransactionDetail")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventorytransactionHdr", "IdtransactionHeadNavigation")
                        .WithMany("Inventorymovement")
                        .HasForeignKey("IdtransactionHead")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Transactionconcepts", "IdtransactionconceptNavigation")
                        .WithMany()
                        .HasForeignKey("IdtransactionconceptNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Transactiontypes", "IdtransactiontypeNavigation")
                        .WithMany("Inventorymovement")
                        .HasForeignKey("Idtransactiontype")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventoryTypes", "IdtypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdtypeNavigationId");

                    b.Navigation("IdbinNavigation");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("IdlocationNavigation");

                    b.Navigation("IdrackNavigation");

                    b.Navigation("IdstatusNavigation");

                    b.Navigation("IdtransactionDetailNavigation");

                    b.Navigation("IdtransactionHeadNavigation");

                    b.Navigation("IdtransactionconceptNavigation");

                    b.Navigation("IdtransactiontypeNavigation");

                    b.Navigation("IdtypeNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionDetail", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Bines", "IdbinNavigation")
                        .WithMany()
                        .HasForeignKey("IdbinNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("InventorytransactionDetail")
                        .HasForeignKey("Idcompany")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventorytransactionHdr", "IdenctransactionNavigation")
                        .WithMany("InventorytransactionDetail")
                        .HasForeignKey("Idenctransaction")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Locations", "IdlocationNavigation")
                        .WithMany("InventorytransactionDetail")
                        .HasForeignKey("Idlocation")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Racks", "IdrackNavigation")
                        .WithMany()
                        .HasForeignKey("IdrackNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Itemstatus", "IdstatusNavigation")
                        .WithMany()
                        .HasForeignKey("IdstatusNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.InventoryTypes", "IdtypeNavigation")
                        .WithMany()
                        .HasForeignKey("IdtypeNavigationId");

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Transactiontypes", "IdtypetransactionNavigation")
                        .WithMany("InventorytransactionDetail")
                        .HasForeignKey("Idtypetransaction")
                        .IsRequired();

                    b.Navigation("IdbinNavigation");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("IdenctransactionNavigation");

                    b.Navigation("IdlocationNavigation");

                    b.Navigation("IdrackNavigation");

                    b.Navigation("IdstatusNavigation");

                    b.Navigation("IdtypeNavigation");

                    b.Navigation("IdtypetransactionNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionHdr", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("InventorytransactionHdr")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Transactionconcepts", "IdtransactionconceptNavigation")
                        .WithMany()
                        .HasForeignKey("IdtransactionconceptNavigationId");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("IdtransactionconceptNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Items", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.CompanyClient", "CompanyClient")
                        .WithMany("Items")
                        .HasForeignKey("CompanyClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Inventorycategories", "InventoryCategory")
                        .WithMany()
                        .HasForeignKey("InventorycategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany()
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyClient");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("InventoryCategory");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Itemstatus", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Itemstatus")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Locations", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Cities", "IdcityNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("Idcity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("Idcompany")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Countries", "IdcountryNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("Idcountry")
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.StatesCountries", "IdstateNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("Idstate")
                        .IsRequired();

                    b.Navigation("IdcityNavigation");

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("IdcountryNavigation");

                    b.Navigation("IdstateNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Racks", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Racks")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUNES.API.ModelsWMS.Masters.Locations", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.StatesCountries", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Countries", "IdcountryNavigation")
                        .WithMany("StatesCountries")
                        .HasForeignKey("Idcountry")
                        .IsRequired();

                    b.Navigation("IdcountryNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Transactionconcepts", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Transactionconcepts")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Transactiontypes", b =>
                {
                    b.HasOne("DUNES.API.ModelsWMS.Masters.Company", "IdcompanyNavigation")
                        .WithMany("Transactiontypes")
                        .HasForeignKey("Idcompany")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdcompanyNavigation");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Cities", b =>
                {
                    b.Navigation("Company");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Company", b =>
                {
                    b.Navigation("Bines");

                    b.Navigation("InventoryTypes");

                    b.Navigation("Inventorycategories");

                    b.Navigation("Inventorydetail");

                    b.Navigation("Inventorymovement");

                    b.Navigation("InventorytransactionDetail");

                    b.Navigation("InventorytransactionHdr");

                    b.Navigation("Itemstatus");

                    b.Navigation("Locations");

                    b.Navigation("Racks");

                    b.Navigation("Transactionconcepts");

                    b.Navigation("Transactiontypes");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.CompanyClient", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Countries", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Company");

                    b.Navigation("Locations");

                    b.Navigation("StatesCountries");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionDetail", b =>
                {
                    b.Navigation("Inventorymovement");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.InventorytransactionHdr", b =>
                {
                    b.Navigation("Inventorymovement");

                    b.Navigation("InventorytransactionDetail");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Locations", b =>
                {
                    b.Navigation("Inventorydetail");

                    b.Navigation("Inventorymovement");

                    b.Navigation("InventorytransactionDetail");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.StatesCountries", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Company");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("DUNES.API.ModelsWMS.Masters.Transactiontypes", b =>
                {
                    b.Navigation("Inventorymovement");

                    b.Navigation("InventorytransactionDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
